/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thrift.test;

import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import java.util.HashMap;
import java.util.Map;

public class BoolTest implements org.apache.thrift.TBase<BoolTest, BoolTest._Fields>, java.io.Serializable, Cloneable {

    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("BoolTest");

    private static final org.apache.thrift.protocol.TField B_FIELD_DESC = new org.apache.thrift.protocol.TField("b", org.apache.thrift.protocol.TType.BOOL, (short) 1);
    private static final org.apache.thrift.protocol.TField S_FIELD_DESC = new org.apache.thrift.protocol.TField("s", org.apache.thrift.protocol.TType.STRING, (short) 2);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();

    static {
        schemes.put(StandardScheme.class, new BoolTestStandardSchemeFactory());
    }

    private boolean b; // optional
    private String s; // optional

    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
        ;

        @Override
        public short getThriftFieldId() {
            return 0;
        }

        @Override
        public String getFieldName() {
            return null;
        }
    }

    // isset id assignments
    private static final int __B_ISSET_ID = 0;
    private byte __isset_bitfield = 0;

    public BoolTest() {
        this.b = true;

        this.s = "true";

    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public BoolTest(BoolTest other) {
        __isset_bitfield = other.__isset_bitfield;
        this.b = other.b;
        if (other.isSetS()) {
            this.s = other.s;
        }
    }

    public BoolTest deepCopy() {
        return new BoolTest(this);
    }

    public void clear() {
        this.b = true;

        this.s = "true";

    }

    public boolean isB() {
        return this.b;
    }

    public void setB(boolean b) {
        this.b = b;
        setBIsSet(true);
    }

    public void unsetB() {
        __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __B_ISSET_ID);
    }

    /**
     * Returns true if field b is set (has been assigned a value) and false otherwise
     */
    public boolean isSetB() {
        return EncodingUtils.testBit(__isset_bitfield, __B_ISSET_ID);
    }

    public void setBIsSet(boolean value) {
        __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __B_ISSET_ID, value);
    }

    public String getS() {
        return this.s;
    }

    public void setS(String s) {
        this.s = s;
    }

    public void unsetS() {
        this.s = null;
    }

    /**
     * Returns true if field s is set (has been assigned a value) and false otherwise
     */
    public boolean isSetS() {
        return this.s != null;
    }

    public void setSIsSet(boolean value) {
        if (!value) {
            this.s = null;
        }
    }

    @Override
    public boolean isSet(_Fields field) {
        return false;
    }

    @Override
    public Object getFieldValue(_Fields field) {
        return null;
    }

    @Override
    public void setFieldValue(_Fields field, Object value) {
    }

    @Override
    public _Fields fieldForId(int fieldId) {
        return null;
    }

    public int compareTo(BoolTest other) {
        return 0;
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws TException {
        schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws TException {
        schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
    }

    public void validate() throws TException {
        // check for required fields
        // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
        try {
            write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
        } catch (TException te) {
            throw new java.io.IOException(te.getMessage());
        }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
        try {
            // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
            __isset_bitfield = 0;
            read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
        } catch (TException te) {
            throw new java.io.IOException(te.getMessage());
        }
    }

    private static class BoolTestStandardSchemeFactory implements SchemeFactory {

        public BoolTestStandardScheme getScheme() {
            return new BoolTestStandardScheme();
        }
    }

    private static class BoolTestStandardScheme extends StandardScheme<BoolTest> {

        public void read(org.apache.thrift.protocol.TProtocol iprot, BoolTest struct) throws TException {
            org.apache.thrift.protocol.TField schemeField;
            iprot.readStructBegin();
            while (true) {
                schemeField = iprot.readFieldBegin();
                if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
                    break;
                }
                switch (schemeField.id) {
                    case 1: // B
                        if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
                            struct.b = iprot.readBool();
                            struct.setBIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 2: // S
                        if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                            struct.s = iprot.readString();
                            struct.setSIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    default:
                        org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                }
                iprot.readFieldEnd();
            }
            iprot.readStructEnd();
            struct.validate();
        }

        public void write(org.apache.thrift.protocol.TProtocol oprot, BoolTest struct) throws TException {
            struct.validate();

            oprot.writeStructBegin(STRUCT_DESC);
            if (struct.isSetB()) {
                oprot.writeFieldBegin(B_FIELD_DESC);
                oprot.writeBool(struct.b);
                oprot.writeFieldEnd();
            }
            if (struct.s != null) {
                if (struct.isSetS()) {
                    oprot.writeFieldBegin(S_FIELD_DESC);
                    oprot.writeString(struct.s);
                    oprot.writeFieldEnd();
                }
            }
            oprot.writeFieldStop();
            oprot.writeStructEnd();
        }

    }

}

