/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thrift.test;

import org.apache.thrift.TException;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ListTypeVersioningV1 implements org.apache.thrift.TBase<ListTypeVersioningV1, ListTypeVersioningV1._Fields>, java.io.Serializable, Cloneable {

    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ListTypeVersioningV1");

    private static final org.apache.thrift.protocol.TField MYINTS_FIELD_DESC = new org.apache.thrift.protocol.TField("myints", org.apache.thrift.protocol.TType.LIST, (short) 1);
    private static final org.apache.thrift.protocol.TField HELLO_FIELD_DESC = new org.apache.thrift.protocol.TField("hello", org.apache.thrift.protocol.TType.STRING, (short) 2);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();

    static {
        schemes.put(StandardScheme.class, new ListTypeVersioningV1StandardSchemeFactory());
    }

    private List<Integer> myints; // required
    private String hello; // required

    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
        ;

        @Override
        public short getThriftFieldId() {
            return 0;
        }

        @Override
        public String getFieldName() {
            return null;
        }
    }

    // isset id assignments
    public ListTypeVersioningV1() {
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public ListTypeVersioningV1(ListTypeVersioningV1 other) {
        if (other.isSetMyints()) {
            List<Integer> __this__myints = new ArrayList<Integer>();
            for (Integer other_element : other.myints) {
                __this__myints.add(other_element);
            }
            this.myints = __this__myints;
        }
        if (other.isSetHello()) {
            this.hello = other.hello;
        }
    }

    public ListTypeVersioningV1 deepCopy() {
        return new ListTypeVersioningV1(this);
    }

    public void clear() {
        this.myints = null;
        this.hello = null;
    }

    public int getMyintsSize() {
        return (this.myints == null) ? 0 : this.myints.size();
    }

    public java.util.Iterator<Integer> getMyintsIterator() {
        return (this.myints == null) ? null : this.myints.iterator();
    }

    public void addToMyints(int elem) {
        if (this.myints == null) {
            this.myints = new ArrayList<Integer>();
        }
        this.myints.add(elem);
    }

    public List<Integer> getMyints() {
        return this.myints;
    }

    public void setMyints(List<Integer> myints) {
        this.myints = myints;
    }

    public void unsetMyints() {
        this.myints = null;
    }

    /**
     * Returns true if field myints is set (has been assigned a value) and false otherwise
     */
    public boolean isSetMyints() {
        return this.myints != null;
    }

    public void setMyintsIsSet(boolean value) {
        if (!value) {
            this.myints = null;
        }
    }

    public String getHello() {
        return this.hello;
    }

    public void setHello(String hello) {
        this.hello = hello;
    }

    public void unsetHello() {
        this.hello = null;
    }

    /**
     * Returns true if field hello is set (has been assigned a value) and false otherwise
     */
    public boolean isSetHello() {
        return this.hello != null;
    }

    public void setHelloIsSet(boolean value) {
        if (!value) {
            this.hello = null;
        }
    }

    @Override
    public boolean isSet(_Fields field) {
        return false;
    }

    @Override
    public Object getFieldValue(_Fields field) {
        return null;
    }

    @Override
    public void setFieldValue(_Fields field, Object value) {
    }

    @Override
    public _Fields fieldForId(int fieldId) {
        return null;
    }

    public int compareTo(ListTypeVersioningV1 other) {
        return 0;
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws TException {
        schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws TException {
        schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
    }

    public void validate() throws TException {
        // check for required fields
        // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
        try {
            write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
        } catch (TException te) {
            throw new java.io.IOException(te.getMessage());
        }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
        try {
            read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
        } catch (TException te) {
            throw new java.io.IOException(te.getMessage());
        }
    }

    private static class ListTypeVersioningV1StandardSchemeFactory implements SchemeFactory {

        public ListTypeVersioningV1StandardScheme getScheme() {
            return new ListTypeVersioningV1StandardScheme();
        }
    }

    private static class ListTypeVersioningV1StandardScheme extends StandardScheme<ListTypeVersioningV1> {

        public void read(org.apache.thrift.protocol.TProtocol iprot, ListTypeVersioningV1 struct) throws TException {
            org.apache.thrift.protocol.TField schemeField;
            iprot.readStructBegin();
            while (true) {
                schemeField = iprot.readFieldBegin();
                if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
                    break;
                }
                switch (schemeField.id) {
                    case 1: // MYINTS
                        if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
                            {
                                org.apache.thrift.protocol.TList _list57 = iprot.readListBegin();
                                struct.myints = new ArrayList<Integer>(_list57.size);
                                for (int _i58 = 0; _i58 < _list57.size; ++_i58) {
                                    int _elem59; // required
                                    _elem59 = iprot.readI32();
                                    struct.myints.add(_elem59);
                                }
                                iprot.readListEnd();
                            }
                            struct.setMyintsIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 2: // HELLO
                        if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                            struct.hello = iprot.readString();
                            struct.setHelloIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    default:
                        org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                }
                iprot.readFieldEnd();
            }
            iprot.readStructEnd();
            struct.validate();
        }

        public void write(org.apache.thrift.protocol.TProtocol oprot, ListTypeVersioningV1 struct) throws TException {
            struct.validate();

            oprot.writeStructBegin(STRUCT_DESC);
            if (struct.myints != null) {
                oprot.writeFieldBegin(MYINTS_FIELD_DESC);
                {
                    oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I32, struct.myints.size()));
                    for (int _iter60 : struct.myints) {
                        oprot.writeI32(_iter60);
                    }
                    oprot.writeListEnd();
                }
                oprot.writeFieldEnd();
            }
            if (struct.hello != null) {
                oprot.writeFieldBegin(HELLO_FIELD_DESC);
                oprot.writeString(struct.hello);
                oprot.writeFieldEnd();
            }
            oprot.writeFieldStop();
            oprot.writeStructEnd();
        }

    }

}

