/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thrift.test;

import org.apache.thrift.TException;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class NestedListsBonk implements org.apache.thrift.TBase<NestedListsBonk, NestedListsBonk._Fields>, java.io.Serializable, Cloneable {

    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("NestedListsBonk");

    private static final org.apache.thrift.protocol.TField BONK_FIELD_DESC = new org.apache.thrift.protocol.TField("bonk", org.apache.thrift.protocol.TType.LIST, (short) 1);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();

    static {
        schemes.put(StandardScheme.class, new NestedListsBonkStandardSchemeFactory());
    }

    private List<List<List<Bonk>>> bonk; // required

    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
        ;

        @Override
        public short getThriftFieldId() {
            return 0;
        }

        @Override
        public String getFieldName() {
            return null;
        }
    }

    // isset id assignments
    public NestedListsBonk() {
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public NestedListsBonk(NestedListsBonk other) {
        if (other.isSetBonk()) {
            List<List<List<Bonk>>> __this__bonk = new ArrayList<List<List<Bonk>>>();
            for (List<List<Bonk>> other_element : other.bonk) {
                List<List<Bonk>> __this__bonk_copy = new ArrayList<List<Bonk>>();
                for (List<Bonk> other_element_element : other_element) {
                    List<Bonk> __this__bonk_copy_copy = new ArrayList<Bonk>();
                    for (Bonk other_element_element_element : other_element_element) {
                        __this__bonk_copy_copy.add(new Bonk(other_element_element_element));
                    }
                    __this__bonk_copy.add(__this__bonk_copy_copy);
                }
                __this__bonk.add(__this__bonk_copy);
            }
            this.bonk = __this__bonk;
        }
    }

    public NestedListsBonk deepCopy() {
        return new NestedListsBonk(this);
    }

    public void clear() {
        this.bonk = null;
    }

    public int getBonkSize() {
        return (this.bonk == null) ? 0 : this.bonk.size();
    }

    public java.util.Iterator<List<List<Bonk>>> getBonkIterator() {
        return (this.bonk == null) ? null : this.bonk.iterator();
    }

    public void addToBonk(List<List<Bonk>> elem) {
        if (this.bonk == null) {
            this.bonk = new ArrayList<List<List<Bonk>>>();
        }
        this.bonk.add(elem);
    }

    public List<List<List<Bonk>>> getBonk() {
        return this.bonk;
    }

    public void setBonk(List<List<List<Bonk>>> bonk) {
        this.bonk = bonk;
    }

    public void unsetBonk() {
        this.bonk = null;
    }

    /**
     * Returns true if field bonk is set (has been assigned a value) and false otherwise
     */
    public boolean isSetBonk() {
        return this.bonk != null;
    }

    public void setBonkIsSet(boolean value) {
        if (!value) {
            this.bonk = null;
        }
    }

    @Override
    public boolean isSet(_Fields field) {
        return false;
    }

    @Override
    public Object getFieldValue(_Fields field) {
        return null;
    }

    @Override
    public void setFieldValue(_Fields field, Object value) {
    }

    @Override
    public _Fields fieldForId(int fieldId) {
        return null;
    }

    public int compareTo(NestedListsBonk other) {
        return 0;
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws TException {
        schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws TException {
        schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
    }

    public void validate() throws TException {
        // check for required fields
        // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
        try {
            write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
        } catch (TException te) {
            throw new java.io.IOException(te.getMessage());
        }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
        try {
            read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
        } catch (TException te) {
            throw new java.io.IOException(te.getMessage());
        }
    }

    private static class NestedListsBonkStandardSchemeFactory implements SchemeFactory {

        public NestedListsBonkStandardScheme getScheme() {
            return new NestedListsBonkStandardScheme();
        }
    }

    private static class NestedListsBonkStandardScheme extends StandardScheme<NestedListsBonk> {

        public void read(org.apache.thrift.protocol.TProtocol iprot, NestedListsBonk struct) throws TException {
            org.apache.thrift.protocol.TField schemeField;
            iprot.readStructBegin();
            while (true) {
                schemeField = iprot.readFieldBegin();
                if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
                    break;
                }
                switch (schemeField.id) {
                    case 1: // BONK
                        if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
                            {
                                org.apache.thrift.protocol.TList _list132 = iprot.readListBegin();
                                struct.bonk = new ArrayList<List<List<Bonk>>>(_list132.size);
                                for (int _i133 = 0; _i133 < _list132.size; ++_i133) {
                                    List<List<Bonk>> _elem134; // required
                                    {
                                        org.apache.thrift.protocol.TList _list135 = iprot.readListBegin();
                                        _elem134 = new ArrayList<List<Bonk>>(_list135.size);
                                        for (int _i136 = 0; _i136 < _list135.size; ++_i136) {
                                            List<Bonk> _elem137; // required
                                            {
                                                org.apache.thrift.protocol.TList _list138 = iprot.readListBegin();
                                                _elem137 = new ArrayList<Bonk>(_list138.size);
                                                for (int _i139 = 0; _i139 < _list138.size; ++_i139) {
                                                    Bonk _elem140; // required
                                                    _elem140 = new Bonk();
                                                    _elem140.read(iprot);
                                                    _elem137.add(_elem140);
                                                }
                                                iprot.readListEnd();
                                            }
                                            _elem134.add(_elem137);
                                        }
                                        iprot.readListEnd();
                                    }
                                    struct.bonk.add(_elem134);
                                }
                                iprot.readListEnd();
                            }
                            struct.setBonkIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    default:
                        org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                }
                iprot.readFieldEnd();
            }
            iprot.readStructEnd();
            struct.validate();
        }

        public void write(org.apache.thrift.protocol.TProtocol oprot, NestedListsBonk struct) throws TException {
            struct.validate();

            oprot.writeStructBegin(STRUCT_DESC);
            if (struct.bonk != null) {
                oprot.writeFieldBegin(BONK_FIELD_DESC);
                {
                    oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.LIST, struct.bonk.size()));
                    for (List<List<Bonk>> _iter141 : struct.bonk) {
                        {
                            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.LIST, _iter141.size()));
                            for (List<Bonk> _iter142 : _iter141) {
                                {
                                    oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, _iter142.size()));
                                    for (Bonk _iter143 : _iter142) {
                                        _iter143.write(oprot);
                                    }
                                    oprot.writeListEnd();
                                }
                            }
                            oprot.writeListEnd();
                        }
                    }
                    oprot.writeListEnd();
                }
                oprot.writeFieldEnd();
            }
            oprot.writeFieldStop();
            oprot.writeStructEnd();
        }

    }

}

