/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thrift.test;

import org.apache.thrift.TException;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class NestedListsI32x2 implements org.apache.thrift.TBase<NestedListsI32x2, NestedListsI32x2._Fields>, java.io.Serializable, Cloneable {

    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("NestedListsI32x2");

    private static final org.apache.thrift.protocol.TField INTEGERLIST_FIELD_DESC = new org.apache.thrift.protocol.TField("integerlist", org.apache.thrift.protocol.TType.LIST, (short) 1);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();

    static {
        schemes.put(StandardScheme.class, new NestedListsI32x2StandardSchemeFactory());
    }

    private List<List<Integer>> integerlist; // required

    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
        ;

        @Override
        public short getThriftFieldId() {
            return 0;
        }

        @Override
        public String getFieldName() {
            return null;
        }
    }

    // isset id assignments
    public NestedListsI32x2() {
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public NestedListsI32x2(NestedListsI32x2 other) {
        if (other.isSetIntegerlist()) {
            List<List<Integer>> __this__integerlist = new ArrayList<List<Integer>>();
            for (List<Integer> other_element : other.integerlist) {
                List<Integer> __this__integerlist_copy = new ArrayList<Integer>();
                for (Integer other_element_element : other_element) {
                    __this__integerlist_copy.add(other_element_element);
                }
                __this__integerlist.add(__this__integerlist_copy);
            }
            this.integerlist = __this__integerlist;
        }
    }

    public NestedListsI32x2 deepCopy() {
        return new NestedListsI32x2(this);
    }

    public void clear() {
        this.integerlist = null;
    }

    public int getIntegerlistSize() {
        return (this.integerlist == null) ? 0 : this.integerlist.size();
    }

    public java.util.Iterator<List<Integer>> getIntegerlistIterator() {
        return (this.integerlist == null) ? null : this.integerlist.iterator();
    }

    public void addToIntegerlist(List<Integer> elem) {
        if (this.integerlist == null) {
            this.integerlist = new ArrayList<List<Integer>>();
        }
        this.integerlist.add(elem);
    }

    public List<List<Integer>> getIntegerlist() {
        return this.integerlist;
    }

    public void setIntegerlist(List<List<Integer>> integerlist) {
        this.integerlist = integerlist;
    }

    public void unsetIntegerlist() {
        this.integerlist = null;
    }

    /**
     * Returns true if field integerlist is set (has been assigned a value) and false otherwise
     */
    public boolean isSetIntegerlist() {
        return this.integerlist != null;
    }

    public void setIntegerlistIsSet(boolean value) {
        if (!value) {
            this.integerlist = null;
        }
    }

    @Override
    public boolean isSet(_Fields field) {
        return false;
    }

    @Override
    public Object getFieldValue(_Fields field) {
        return null;
    }

    @Override
    public void setFieldValue(_Fields field, Object value) {
    }

    @Override
    public _Fields fieldForId(int fieldId) {
        return null;
    }

    public int compareTo(NestedListsI32x2 other) {
        return 0;
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws TException {
        schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws TException {
        schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
    }

    public void validate() throws TException {
        // check for required fields
        // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
        try {
            write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
        } catch (TException te) {
            throw new java.io.IOException(te.getMessage());
        }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
        try {
            read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
        } catch (TException te) {
            throw new java.io.IOException(te.getMessage());
        }
    }

    private static class NestedListsI32x2StandardSchemeFactory implements SchemeFactory {

        public NestedListsI32x2StandardScheme getScheme() {
            return new NestedListsI32x2StandardScheme();
        }
    }

    private static class NestedListsI32x2StandardScheme extends StandardScheme<NestedListsI32x2> {

        public void read(org.apache.thrift.protocol.TProtocol iprot, NestedListsI32x2 struct) throws TException {
            org.apache.thrift.protocol.TField schemeField;
            iprot.readStructBegin();
            while (true) {
                schemeField = iprot.readFieldBegin();
                if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
                    break;
                }
                switch (schemeField.id) {
                    case 1: // INTEGERLIST
                        if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
                            {
                                org.apache.thrift.protocol.TList _list78 = iprot.readListBegin();
                                struct.integerlist = new ArrayList<List<Integer>>(_list78.size);
                                for (int _i79 = 0; _i79 < _list78.size; ++_i79) {
                                    List<Integer> _elem80; // required
                                    {
                                        org.apache.thrift.protocol.TList _list81 = iprot.readListBegin();
                                        _elem80 = new ArrayList<Integer>(_list81.size);
                                        for (int _i82 = 0; _i82 < _list81.size; ++_i82) {
                                            int _elem83; // required
                                            _elem83 = iprot.readI32();
                                            _elem80.add(_elem83);
                                        }
                                        iprot.readListEnd();
                                    }
                                    struct.integerlist.add(_elem80);
                                }
                                iprot.readListEnd();
                            }
                            struct.setIntegerlistIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    default:
                        org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                }
                iprot.readFieldEnd();
            }
            iprot.readStructEnd();
            struct.validate();
        }

        public void write(org.apache.thrift.protocol.TProtocol oprot, NestedListsI32x2 struct) throws TException {
            struct.validate();

            oprot.writeStructBegin(STRUCT_DESC);
            if (struct.integerlist != null) {
                oprot.writeFieldBegin(INTEGERLIST_FIELD_DESC);
                {
                    oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.LIST, struct.integerlist.size()));
                    for (List<Integer> _iter84 : struct.integerlist) {
                        {
                            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I32, _iter84.size()));
                            for (int _iter85 : _iter84) {
                                oprot.writeI32(_iter85);
                            }
                            oprot.writeListEnd();
                        }
                    }
                    oprot.writeListEnd();
                }
                oprot.writeFieldEnd();
            }
            oprot.writeFieldStop();
            oprot.writeStructEnd();
        }

    }

}

